[Icon Theme]
Name=Näher zu Jesus Pixel
Comment=8-Bit-Ordner und -Dateien im Sonnenaufgangs-Stil
Example=folder
Inherits=Adwaita,hicolor

Directories=scalable/places,scalable/mimetypes,symbolic

[symbolic]
Context=Actions
Size=16
MinSize=8
MaxSize=512
Type=Scalable

[scalable/places]
Context=Places
Size=64
MinSize=8
MaxSize=512
Type=Scalable

[scalable/mimetypes]
Context=MimeTypes
Size=64
MinSize=8
MaxSize=512
Type=Scalable
